//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinPSK.rc
//
#define IDS_DLLNOTFOUND                 1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_WINPSK_FORM                 101
#define IDC_THEIRCALL                   101
#define IDC_THEIRNAME                   102
#define IDC_TEXTGRAB                    103
#define CG_IDS_DISK_SPACE               106
#define CG_IDS_DISK_SPACE_UNAVAIL       107
#define IDR_MAINFRAME                   128
#define IDR_WINPSKTYPE                  129
#define IDD_EDIT1                       130
#define IDR_RCVCLIPMENU                 131
#define IDR_XMITCLIPMENU                132
#define IDI_TRXMIT                      134
#define IDI_TRRCV                       135
#define IDI_TROFF                       136
#define IDI_TUNE                        138
#define IDD_MACRODIALOG                 139
#define IDD_GENSETUP                    140
#define IDI_TXFINISH                    142
#define IDD_WAVEDIALOG                  143
#define IDI_STOP                        146
#define IDI_START                       147
#define IDC_TRBUTTON                    1000
#define IDC_BPSK                        1001
#define IDC_RICHEDIT1                   1002
#define IDC_QPSK                        1002
#define IDC_DISPLAYTAB                  1003
#define IDC_RICHEDIT2                   1003
#define IDC_PLOTAREA                    1004
#define IDC_RICHEDIT3                   1004
#define IDC_RICHEDIT4                   1005
#define IDC_RICHEDIT5                   1006
#define IDC_RXFREQ                      1007
#define IDC_ZOOM                        1008
#define IDC_RXFREQSPIN                  1009
#define IDC_AFC                         1010
#define IDC_TXFREQSPIN                  1011
#define IDC_NET                         1013
#define IDC_TXFREQ                      1015
#define IDC_M1BUTTON                    1017
#define IDC_XMINTXT                     1018
#define IDC_M2BUTTON                    1019
#define IDC_XMAXTXT                     1020
#define IDC_M3BUTTON                    1021
#define IDC_M4BUTTON                    1022
#define IDC_M5BUTTON                    1024
#define IDC_ZOOMTXT                     1025
#define IDC_SLOWAVE                     1026
#define IDC_M6BUTTON                    1027
#define IDC_M7BUTTON                    1028
#define IDC_M8BUTTON                    1029
#define IDC_M9BUTTON                    1030
#define IDC_M10BUTTON                   1032
#define IDC_TITLE_EDIT                  1038
#define IDC_MACROEDIT                   1039
#define IDC_CALLSIGNEDIT                1040
#define IDC_USESLASH                    1041
#define IDC_PTTNONE                     1042
#define IDC_PTTCOM1                     1043
#define IDC_PTTCOM2                     1044
#define IDC_PTTCOM3                     1045
#define IDC_PTTCOM4                     1046
#define IDC_USELSB                      1047
#define IDC_SQUELCH                     1048
#define IDC_ECHOTXTEXT                  1048
#define IDC_USELOCALTIME                1049
#define IDC_PTTCOM5                     1050
#define IDC_PTTCOM6                     1051
#define IDC_PTTCOM7                     1052
#define IDC_PTTCOM8                     1053
#define IDC_SATMODE                     1054
#define IDC_DISK_SPACE                  1056
#define IDC_CLKADJ                      1057
#define IDC_CLKADJSPIN                  1058
#define IDC_STARTFREQSPIN               1059
#define IDC_STARTFREQ                   1060
#define IDC_ENDFREQSPIN                 1061
#define IDC_AUTOTXTSEL                  1062
#define IDC_ENDFREQ                     1062
#define IDC_CLRQSO                      1063
#define IDC_AFCSPIN                     1063
#define IDC_AFCLIMIT                    1064
#define IDC_INCFNSET                    1065
#define IDC_SQSPIN                      1065
#define IDC_DECFNSET                    1066
#define IDC_SQSPEED                     1066
#define IDC_MACROSETTXT                 1067
#define IDC_COREVERSION                 1068
#define IDC_FREESC                      1069
#define IDC_PRIMSC                      1070
#define IDC_SETHOME                     1070
#define IDC_SECONDSC                    1071
#define IDC_DEBUGTXT1                   1071
#define IDC_DEBUGTXT2                   1072
#define IDC_SELECTREADFILE              1072
#define IDC_WAVEREADPATH                1073
#define IDC_INOFFSET                    1074
#define IDC_INFILEDATA                  1075
#define IDC_SELECTOUTFILE               1076
#define IDC_WAVEWRITEPATH               1077
#define IDC_OUTPUTAPPEND                1078
#define IDC_WAVESRC                     1079
#define IDC_SOUNDSRC                    1080
#define IDC_LOGINPUT                    1081
#define IDC_LOGTX                       1082
#define IDC_NOSOUNDOUT                  1083
#define IDC_RUN                         1084
#define IDC_OUTLIMIT                    1084
#define IDC_ECHOINPUT                   1085
#define IDC_TXFMODE                     1085
#define IDC_PALBUTTON                   1086
#define IDC_PALTXT                      1087
#define IDC_PSK3163                     1093
#define ID_CANCEL_EDIT_CNTR             32768
#define IDM_CLEARXMIT                   32773
#define IDM_RCVFONT                     32775
#define IDM_XMITFONT                    32776
#define IDM_RCVBACKCOLOR                32777
#define IDM_XMITBACKCOLOR               32778
#define IDM_XMITSENTFONT                32780
#define ID_SETTINGS_CALLSIGNSETUP       32782
#define IDM_CLEARRCV                    32783
#define ID_SETUP                        32784
#define IDM_STOP                        32785
#define ID_HELP_TOPICS                  32787
#define ID_RCVLVLSETUP                  32789
#define ID_TXLVLSETUP                   32790
#define ID_RXLVLSETUP                   32791
#define IDM_TXTUNE                      32792
#define IDM_SENDFILE                    32793
#define ID_VIEW_STAYONTOP               32802
#define IDM_SELREADFILE                 32803
#define IDM_SELWAVEFILES                32804
#define IDS_TESTMODESTRING              57346
#define IDS_STATUSBAR1                  60000
#define IDS_STATUSBAR2                  60001
#define IDS_STATUSBAR3                  60002
#define IDS_STATUSBAR4                  60003
#define ID_INDICATOR_STATUS             60004
#define IDM_PTTSETUP                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
